branch-defaults:
  master:
    environment: MWC-APP-dev
    group_suffix: null
global:
  application_name: MWC_APP
  branch: null
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
  WSGIPath: MWC_APP/MWC_APP/wsgi.py
