# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20171015_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_field',
            field=models.TextField(null=True),
        ),
    ]
