# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20171015_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='franchises.Franchise'),
        ),
    ]
