# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
