# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20170914_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
