# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20170914_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_child_model',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name',
                 models.CharField(
                     max_length=10)),
                ('customer',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='customers.Customer')),
            ],
        ),
    ]
