# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_test_child_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_child_model',
            name='customer',
        ),
        migrations.DeleteModel(
            name='test_child_model',
        ),
    ]
