# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20170915_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='frequency',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (4, 4), (8, 8), (12, 12), (16, 16), (20, 20), (24, 24), (26, 26), (52, 52)], default=4),
            preserve_default=False,
        ),
    ]
