# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0001_initial'),
        ('customers', '0013_auto_20170913_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='franchises.Franchise'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Property_type'),
        ),
    ]
