# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_auto_20170913_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='franchise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='franchises.Franchise'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='property_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='customers.Property_type'),
            preserve_default=False,
        ),
    ]
