# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 17:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_status', models.IntegerField()),
                ('job_status_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('allocated_date', models.DateField(null=True)),
                ('completed_date', models.DateField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('frequency', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (4, 4), (8, 8), (12, 12), (16, 16), (20, 20), (24, 24), (26, 26), (52, 52)])),
                ('job_notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='customers.Customer')),
                ('job_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksheets.Job_status')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.IntegerField()),
                ('payment_status_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='payment_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='worksheets.Payment_status'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='window_cleaner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
