# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_status',
            name='job_status',
        ),
        migrations.RemoveField(
            model_name='payment_status',
            name='payment_status',
        ),
    ]
