# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20170909_1731'),
        ('worksheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_status', models.IntegerField()),
                ('job_status_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.IntegerField()),
                ('payment_status_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='worksheets.Job_status'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='payment_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='worksheets.Payment_status'),
        ),
    ]
