# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 15:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0002_auto_20170914_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='allocated_date',
            field=models.DateField(
                blank=True,
                null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='completed_date',
            field=models.DateField(
                blank=True,
                null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='payment_status',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='worksheets.Payment_status'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='window_cleaner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='jobs',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
