# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0003_auto_20170915_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'ordering': ['-scheduled_date']},
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='frequency',
        ),
    ]
