# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 16:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0003_auto_20170909_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='allocated_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='completed_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksheets.Job_status'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='window_cleaner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
