# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0004_auto_20170909_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer'),
        ),
    ]
