# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0005_auto_20170920_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='invoiced',
            field=models.BooleanField(default=False),
        ),
    ]
