# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 14:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0005_auto_20170909_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='customers.Customer'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='window_cleaner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
